// Simple ROOT file reader generated by delila2root

#include <TFile.h>
#include <TTree.h>

#include <iostream>
#include <string>
#include <vector>

void simple_reader(std::string fileName = "run0160.root")
{
  auto file = TFile::Open(fileName.c_str(), "READ");
  auto tree = file->Get<TTree>("delila");
  const auto nEntries = tree->GetEntries();
  std::cout << "Number of entries: " << nEntries << std::endl;
  tree->SetBranchStatus("*", 0);  // Disable all branches

  Int_t n;
  tree->SetBranchStatus("n", 1);
  tree->SetBranchAddress("n", &n);

  // The max array size. If the data is bigger than this, you will get segmentation fault.
  constexpr size_t max_size = 1024 * 16;
  UChar_t ModArray[max_size];
  tree->SetBranchStatus("Mod", 1);
  tree->SetBranchAddress("Mod", ModArray);

  UChar_t ChArray[max_size];
  tree->SetBranchStatus("Ch", 1);
  tree->SetBranchAddress("Ch", ChArray);

  Double_t TimestampArray[max_size];
  tree->SetBranchStatus("Timestamp", 1);
  tree->SetBranchAddress("Timestamp", TimestampArray);

  for (Long64_t i = 0; i < nEntries; i++) {
    tree->GetEntry(i);
    std::cout << "Entry " << i << ": n=" << n << std::endl;

    for (size_t j = 0; j < n; j++) {
      if (ModArray[j] == 0 && ChArray[j] == 0)
        std::cout << "  Mod=" << Int_t(ModArray[j])
                  << ", Ch=" << Int_t(ChArray[j])
                  << ", Timestamp=" << TimestampArray[j] << std::endl;
    }
  }

  file->Close();
}