//! AUTO-GENERATED by `cargo run --bin amax_codegen`. Do not edit by hand.
//!
//! Sources:
//! - 2026_pid/AMAX_firmware32_channel_4input_caenlist/output/output/RegisterFile_21last.json
//! - (addresses only)
//!
//! AMax custom-firmware register address map. Byte address =
//! `(PAGE_BASE + channel * PAGE_STRIDE + word_offset) * 4` per the
//! FELib `SetUserRegister` ABI used by `tools/amax_viewer/`.

/// Channel-page base in word units (channel 0).
pub const PAGE_BASE: u32 = 0x100000;

/// Word stride between consecutive channel pages.
pub const PAGE_STRIDE: u32 = 0x0;

// ---- Per-channel register offsets (word, relative to the channel page base) ----

/// 1-bit Wave Selector
pub const REG_SELECTOR_WAVE: u32 = 0x0;
/// 32-bit Pretrig Input
pub const REG_PRETRIGGER_INPUT: u32 = 0x1;
/// 1-bit Polarity
pub const REG_POLARITY: u32 = 0x2;
/// 16-bit DC Offset
pub const REG_OFFSET: u32 = 0x3;
/// 32-bit Threshold
pub const REG_THRS: u32 = 0x4;
/// 16-bit Fast Trig Rise
pub const REG_TRIG_K: u32 = 0x5;
/// 16-bit Fast Trig Decay
pub const REG_TRIG_M: u32 = 0x6;
/// 16-bit Trap Rise
pub const REG_TRAP_K: u32 = 0x7;
/// 16-bit Trap Decay
pub const REG_TRAP_M: u32 = 0x8;
/// 24-bit Deconvolution
pub const REG_DECONV_M: u32 = 0x9;
/// 24-bit Trap Gain
pub const REG_TRAP_GAIN: u32 = 0xA;
/// 4-bit BL Length (MCA)
pub const REG_BL_LEN: u32 = 0xB;
/// 16-bit BL Inhibit
pub const REG_BL_INIB: u32 = 0xC;
/// 16-bit Sample Pos
pub const REG_SAMPLE_POS: u32 = 0xD;
/// 1-bit Run Enable
pub const REG_RUN_CFG: u32 = 0xF;
/// 32-bit AMax Window
pub const REG_AMAX_WINDOW: u32 = 0x12;
/// 32-bit Max Window
pub const REG_WINDOW_MAXIM: u32 = 0x14;
/// 16-bit AMax Length
pub const REG_AMAX_LEN: u32 = 0x15;
/// 32-bit BL Delay (AMax)
pub const REG_BASELINE_DELAY: u32 = 0x17;
/// 16-bit BL Length (AMax)
pub const REG_BASELINE_LEN: u32 = 0x18;
/// 16-bit BL Offset (AMax)
pub const REG_BASELINE_OFFSET: u32 = 0x19;
/// 32-bit Pretrig Trap
pub const REG_PRETRIGGER_TRAP: u32 = 0x1E;
/// 32-bit Pretrig AMax
pub const REG_PRETRIGGER_AMAX: u32 = 0x1F;
/// 32-bit Delay Shaping
pub const REG_DELAY_SHAPING: u32 = 0x21;
/// 16-bit Shaping Trigger
pub const REG_SHAP_TRIGG: u32 = 0xC0040;
/// 16-bit Shaping BL Hold
pub const REG_SHAP_BL_HOLD: u32 = 0xC0041;

/// Compute the FELib byte address for a per-channel register.
#[inline]
pub fn channel_register_byte_addr(channel: u8, word_offset: u32) -> u32 {
    let word_addr = PAGE_BASE + (channel as u32) * PAGE_STRIDE + word_offset;
    word_addr * 4
}

/// All writable per-channel register fields, in stable order.
/// Used by `apply_amax_channel_config` to drive `set_user_register` calls.
#[allow(dead_code)]
pub fn channel_writes(
    config: &crate::config::digitizer::AMaxChannelConfig,
) -> Vec<(u32, u32, &'static str)> {
    let mut writes = Vec::new();
    if let Some(v) = config.selector_wave { writes.push((REG_SELECTOR_WAVE, v, "selector_wave")); }
    if let Some(v) = config.pretrigger_input { writes.push((REG_PRETRIGGER_INPUT, v, "pretrigger_input")); }
    if let Some(v) = config.polarity { writes.push((REG_POLARITY, v, "polarity")); }
    if let Some(v) = config.offset { writes.push((REG_OFFSET, v, "offset")); }
    if let Some(v) = config.thrs { writes.push((REG_THRS, v, "thrs")); }
    if let Some(v) = config.trig_k { writes.push((REG_TRIG_K, v, "trig_k")); }
    if let Some(v) = config.trig_m { writes.push((REG_TRIG_M, v, "trig_m")); }
    if let Some(v) = config.trap_k { writes.push((REG_TRAP_K, v, "trap_k")); }
    if let Some(v) = config.trap_m { writes.push((REG_TRAP_M, v, "trap_m")); }
    if let Some(v) = config.deconv_m { writes.push((REG_DECONV_M, v, "deconv_m")); }
    if let Some(v) = config.trap_gain { writes.push((REG_TRAP_GAIN, v, "trap_gain")); }
    if let Some(v) = config.bl_len { writes.push((REG_BL_LEN, v, "bl_len")); }
    if let Some(v) = config.bl_inib { writes.push((REG_BL_INIB, v, "bl_inib")); }
    if let Some(v) = config.sample_pos { writes.push((REG_SAMPLE_POS, v, "sample_pos")); }
    if let Some(v) = config.run_cfg { writes.push((REG_RUN_CFG, v, "run_cfg")); }
    if let Some(v) = config.amax_window { writes.push((REG_AMAX_WINDOW, v, "amax_window")); }
    if let Some(v) = config.window_maxim { writes.push((REG_WINDOW_MAXIM, v, "window_maxim")); }
    if let Some(v) = config.amax_len { writes.push((REG_AMAX_LEN, v, "amax_len")); }
    if let Some(v) = config.baseline_delay { writes.push((REG_BASELINE_DELAY, v, "baseline_delay")); }
    if let Some(v) = config.baseline_len { writes.push((REG_BASELINE_LEN, v, "baseline_len")); }
    if let Some(v) = config.baseline_offset { writes.push((REG_BASELINE_OFFSET, v, "baseline_offset")); }
    if let Some(v) = config.pretrigger_trap { writes.push((REG_PRETRIGGER_TRAP, v, "pretrigger_trap")); }
    if let Some(v) = config.pretrigger_amax { writes.push((REG_PRETRIGGER_AMAX, v, "pretrigger_amax")); }
    if let Some(v) = config.delay_shaping { writes.push((REG_DELAY_SHAPING, v, "delay_shaping")); }
    if let Some(v) = config.shap_trigg { writes.push((REG_SHAP_TRIGG, v, "shap_trigg")); }
    if let Some(v) = config.shap_bl_hold { writes.push((REG_SHAP_BL_HOLD, v, "shap_bl_hold")); }
    writes
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn register_offsets_are_distinct() {
        let offsets = [
            REG_SELECTOR_WAVE,
            REG_PRETRIGGER_INPUT,
            REG_POLARITY,
            REG_OFFSET,
            REG_THRS,
            REG_TRIG_K,
            REG_TRIG_M,
            REG_TRAP_K,
            REG_TRAP_M,
            REG_DECONV_M,
            REG_TRAP_GAIN,
            REG_BL_LEN,
            REG_BL_INIB,
            REG_SAMPLE_POS,
            REG_RUN_CFG,
            REG_AMAX_WINDOW,
            REG_WINDOW_MAXIM,
            REG_AMAX_LEN,
            REG_BASELINE_DELAY,
            REG_BASELINE_LEN,
            REG_BASELINE_OFFSET,
            REG_PRETRIGGER_TRAP,
            REG_PRETRIGGER_AMAX,
            REG_DELAY_SHAPING,
            REG_SHAP_TRIGG,
            REG_SHAP_BL_HOLD,
        ];
        let mut sorted = offsets.to_vec();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(sorted.len(), offsets.len());
    }

    #[test]
    fn channel_addr_math() {
        // ch0 base byte addr = PAGE_BASE * 4 (word→byte).
        assert_eq!(channel_register_byte_addr(0, 0), PAGE_BASE * 4);
        // Each channel index advances by PAGE_STRIDE words (=4× bytes).
        assert_eq!(
            channel_register_byte_addr(1, 0),
            channel_register_byte_addr(0, 0) + PAGE_STRIDE * 4
        );
    }
}
