//! AUTO-GENERATED by `cargo run --bin amax_codegen`. Do not edit by hand.
//!
//! Sources:
//! - FW/16June2026/RegisterFile.json
//! - (addresses only)
//!
//! AMax custom-firmware register address map. Byte address =
//! `(PAGE_BASE + channel * PAGE_STRIDE + word_offset) * 4` per the
//! FELib `SetUserRegister` ABI used by `tools/amax_viewer/`.

/// Channel-page base in word units (channel 0).
pub const PAGE_BASE: u32 = 0x4000;

/// Word stride between consecutive channel pages.
pub const PAGE_STRIDE: u32 = 0x200;

// ---- Per-channel register offsets (word, relative to the channel page base) ----

/// 32-bit Pretrig Input
pub const REG_PRETRIGGER_INPUT: u32 = 0x0;
/// 1-bit Polarity
pub const REG_POLARITY: u32 = 0x1;
/// 16-bit DC Offset
pub const REG_OFFSET: u32 = 0x2;
/// 32-bit Threshold
pub const REG_THRS: u32 = 0x3;
/// 16-bit Fast Trig Rise
pub const REG_TRIG_K: u32 = 0x4;
/// 16-bit Fast Trig Decay
pub const REG_TRIG_M: u32 = 0x5;
/// 16-bit Trap Rise
pub const REG_TRAP_K: u32 = 0x6;
/// 16-bit Trap Decay
pub const REG_TRAP_M: u32 = 0x7;
/// 24-bit Deconvolution
pub const REG_DECONV_M: u32 = 0x8;
/// 24-bit Trap Gain
pub const REG_TRAP_GAIN: u32 = 0x9;
/// 4-bit BL Length (MCA)
pub const REG_BL_LEN: u32 = 0xA;
/// 16-bit BL Inhibit
pub const REG_BL_INIB: u32 = 0xB;
/// 16-bit Sample Pos
pub const REG_SAMPLE_POS: u32 = 0xC;
/// 1-bit Run Enable
pub const REG_RUN_CFG: u32 = 0xD;
/// 32-bit AMax Window
pub const REG_AMAX_WINDOW: u32 = 0xE;
/// 32-bit Max Window
pub const REG_WINDOW_MAXIM: u32 = 0xF;
/// 16-bit AMax Length
pub const REG_AMAX_LEN: u32 = 0x10;
/// 32-bit BL Delay (AMax)
pub const REG_BASELINE_DELAY: u32 = 0x11;
/// 16-bit BL Length (AMax)
pub const REG_BASELINE_LEN: u32 = 0x12;
/// 16-bit BL Offset (AMax)
pub const REG_BASELINE_OFFSET: u32 = 0x13;
/// 32-bit Delay Shaping
pub const REG_DELAY_SHAPING: u32 = 0x15;
/// 32-bit Shaping Trigger
pub const REG_SHAP_TRIGG: u32 = 0x16;
/// 32-bit Delay Debug
pub const REG_DELAY_DEBUG: u32 = 0x18;
/// 1-bit Enable Acquisition
pub const REG_ENABLE_ACQ: u32 = 0x19;
/// 8-bit E-Gate Trigger Sel
pub const REG_SEL_TRIGGER: u32 = 0x100;
/// 16-bit AMax Gate Min
pub const REG_MIN_AMAX: u32 = 0x101;
/// 16-bit Energy Gate Max
pub const REG_MAX_ENERGY: u32 = 0x102;
/// 16-bit Energy Gate Min
pub const REG_MIN_ENERGY: u32 = 0x103;
/// 16-bit AMax Gate Max
pub const REG_MAX_AMAX: u32 = 0x104;

/// Compute the FELib byte address for a per-channel register.
#[inline]
pub fn channel_register_byte_addr(channel: u8, word_offset: u32) -> u32 {
    let word_addr = PAGE_BASE + (channel as u32) * PAGE_STRIDE + word_offset;
    word_addr * 4
}

/// All writable per-channel register fields, in stable order.
/// Used by `apply_amax_channel_config` to drive `set_user_register` calls.
#[allow(dead_code)]
pub fn channel_writes(
    config: &crate::config::digitizer::AMaxChannelConfig,
) -> Vec<(u32, u32, &'static str)> {
    let mut writes = Vec::new();
    if let Some(v) = config.pretrigger_input {
        writes.push((REG_PRETRIGGER_INPUT, v, "pretrigger_input"));
    }
    if let Some(v) = config.polarity {
        writes.push((REG_POLARITY, v, "polarity"));
    }
    if let Some(v) = config.offset {
        writes.push((REG_OFFSET, v, "offset"));
    }
    if let Some(v) = config.thrs {
        writes.push((REG_THRS, v, "thrs"));
    }
    if let Some(v) = config.trig_k {
        writes.push((REG_TRIG_K, v, "trig_k"));
    }
    if let Some(v) = config.trig_m {
        writes.push((REG_TRIG_M, v, "trig_m"));
    }
    if let Some(v) = config.trap_k {
        writes.push((REG_TRAP_K, v, "trap_k"));
    }
    if let Some(v) = config.trap_m {
        writes.push((REG_TRAP_M, v, "trap_m"));
    }
    if let Some(v) = config.deconv_m {
        writes.push((REG_DECONV_M, v, "deconv_m"));
    }
    if let Some(v) = config.trap_gain {
        writes.push((REG_TRAP_GAIN, v, "trap_gain"));
    }
    if let Some(v) = config.bl_len {
        writes.push((REG_BL_LEN, v, "bl_len"));
    }
    if let Some(v) = config.bl_inib {
        writes.push((REG_BL_INIB, v, "bl_inib"));
    }
    if let Some(v) = config.sample_pos {
        writes.push((REG_SAMPLE_POS, v, "sample_pos"));
    }
    if let Some(v) = config.run_cfg {
        writes.push((REG_RUN_CFG, v, "run_cfg"));
    }
    if let Some(v) = config.amax_window {
        writes.push((REG_AMAX_WINDOW, v, "amax_window"));
    }
    if let Some(v) = config.window_maxim {
        writes.push((REG_WINDOW_MAXIM, v, "window_maxim"));
    }
    if let Some(v) = config.amax_len {
        writes.push((REG_AMAX_LEN, v, "amax_len"));
    }
    if let Some(v) = config.baseline_delay {
        writes.push((REG_BASELINE_DELAY, v, "baseline_delay"));
    }
    if let Some(v) = config.baseline_len {
        writes.push((REG_BASELINE_LEN, v, "baseline_len"));
    }
    if let Some(v) = config.baseline_offset {
        writes.push((REG_BASELINE_OFFSET, v, "baseline_offset"));
    }
    if let Some(v) = config.delay_shaping {
        writes.push((REG_DELAY_SHAPING, v, "delay_shaping"));
    }
    if let Some(v) = config.shap_trigg {
        writes.push((REG_SHAP_TRIGG, v, "shap_trigg"));
    }
    if let Some(v) = config.delay_debug {
        writes.push((REG_DELAY_DEBUG, v, "delay_debug"));
    }
    if let Some(v) = config.enable_acq {
        writes.push((REG_ENABLE_ACQ, v, "enable_acq"));
    }
    if let Some(v) = config.sel_trigger {
        writes.push((REG_SEL_TRIGGER, v, "sel_trigger"));
    }
    if let Some(v) = config.min_amax {
        writes.push((REG_MIN_AMAX, v, "min_amax"));
    }
    if let Some(v) = config.max_energy {
        writes.push((REG_MAX_ENERGY, v, "max_energy"));
    }
    if let Some(v) = config.min_energy {
        writes.push((REG_MIN_ENERGY, v, "min_energy"));
    }
    if let Some(v) = config.max_amax {
        writes.push((REG_MAX_AMAX, v, "max_amax"));
    }
    writes
}

/// All writable board-level register fields, in stable order.
/// Mirror of `channel_writes` for `AMaxBoardConfig`. Each tuple is
/// (BOARD_REG byte address, value, field_name). Empty when no
/// board-level (global) registers are declared in fw_params.json.
#[allow(dead_code)]
pub fn board_writes(
    _config: &crate::config::digitizer::AMaxBoardConfig,
) -> Vec<(u32, u32, &'static str)> {
    #[allow(unused_mut)]
    let mut writes = Vec::new();
    writes
}

/// All board-level register (byte_addr, name) pairs, in stable order.
/// Used by the operator UI's Tune Up debug view to read live
/// values back from the digitizer (see
/// `ReadLoopRequest::ReadAmaxBoardRegisters` in `reader/mod.rs`).
/// Empty when no board-level registers are declared.
#[allow(dead_code)]
pub fn all_board_registers() -> Vec<(u32, &'static str)> {
    vec![]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn register_offsets_are_distinct() {
        let offsets = [
            REG_PRETRIGGER_INPUT,
            REG_POLARITY,
            REG_OFFSET,
            REG_THRS,
            REG_TRIG_K,
            REG_TRIG_M,
            REG_TRAP_K,
            REG_TRAP_M,
            REG_DECONV_M,
            REG_TRAP_GAIN,
            REG_BL_LEN,
            REG_BL_INIB,
            REG_SAMPLE_POS,
            REG_RUN_CFG,
            REG_AMAX_WINDOW,
            REG_WINDOW_MAXIM,
            REG_AMAX_LEN,
            REG_BASELINE_DELAY,
            REG_BASELINE_LEN,
            REG_BASELINE_OFFSET,
            REG_DELAY_SHAPING,
            REG_SHAP_TRIGG,
            REG_DELAY_DEBUG,
            REG_ENABLE_ACQ,
            REG_SEL_TRIGGER,
            REG_MIN_AMAX,
            REG_MAX_ENERGY,
            REG_MIN_ENERGY,
            REG_MAX_AMAX,
        ];
        let mut sorted = offsets.to_vec();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(sorted.len(), offsets.len());
    }

    #[test]
    fn channel_addr_math() {
        // ch0 base byte addr = PAGE_BASE * 4 (word→byte).
        assert_eq!(channel_register_byte_addr(0, 0), PAGE_BASE * 4);
        // Each channel index advances by PAGE_STRIDE words (=4× bytes).
        assert_eq!(
            channel_register_byte_addr(1, 0),
            channel_register_byte_addr(0, 0) + PAGE_STRIDE * 4
        );
    }
}
