//! AUTO-GENERATED by `cargo run --bin amax_codegen`. Do not edit by hand.
//!
//! Sources:
//! - AMAX_firmware32_channel_4input_caenlist/output/output/RegisterFile.json
//! - (addresses only)
//!
//! AMax custom-firmware register address map. Byte address =
//! `(PAGE_BASE + channel * PAGE_STRIDE + word_offset) * 4` per the
//! FELib `SetUserRegister` ABI used by `tools/amax_viewer/`.

/// Channel-page base in word units (channel 0).
pub const PAGE_BASE: u32 = 0x800000;

/// Word stride between consecutive channel pages.
pub const PAGE_STRIDE: u32 = 0x40000;

// ---- Per-channel register offsets (word, relative to the channel page base) ----

/// 1-bit Wave Selector
pub const REG_SELECTOR_WAVE: u32 = 0x00;
/// 32-bit Pretrig Input
pub const REG_PRETRIGGER_INPUT: u32 = 0x01;
/// 1-bit Polarity
pub const REG_POLARITY: u32 = 0x02;
/// 16-bit DC Offset
pub const REG_OFFSET: u32 = 0x03;
/// 32-bit Threshold
pub const REG_THRS: u32 = 0x04;
/// 16-bit Fast Trig Rise
pub const REG_TRIG_K: u32 = 0x05;
/// 16-bit Fast Trig Decay
pub const REG_TRIG_M: u32 = 0x06;
/// 16-bit Trap Rise
pub const REG_TRAP_K: u32 = 0x07;
/// 16-bit Trap Decay
pub const REG_TRAP_M: u32 = 0x08;
/// 24-bit Deconvolution
pub const REG_DECONV_M: u32 = 0x09;
/// 24-bit Trap Gain
pub const REG_TRAP_GAIN: u32 = 0x0A;
/// 4-bit BL Length (MCA)
pub const REG_BL_LEN: u32 = 0x0B;
/// 16-bit BL Inhibit
pub const REG_BL_INIB: u32 = 0x0C;
/// 16-bit Sample Pos
pub const REG_SAMPLE_POS: u32 = 0x0D;
/// 1-bit Run Enable
pub const REG_RUN_CFG: u32 = 0x0F;
/// 32-bit AMax Window
pub const REG_AMAX_WINDOW: u32 = 0x12;
/// 32-bit AMax Delay
pub const REG_AMAX_DELAY: u32 = 0x14;
/// 32-bit Max Window
pub const REG_WINDOW_MAXIM: u32 = 0x15;
/// 16-bit AMax Length
pub const REG_AMAX_LEN: u32 = 0x16;
/// 32-bit BL Delay (AMax)
pub const REG_BASELINE_DELAY: u32 = 0x18;
/// 16-bit BL Length (AMax)
pub const REG_BASELINE_LEN: u32 = 0x19;
/// 16-bit BL Offset (AMax)
pub const REG_BASELINE_OFFSET: u32 = 0x1A;
/// 32-bit Pretrig Trap
pub const REG_PRETRIGGER_TRAP: u32 = 0x1F;
/// 32-bit Pretrig AMax
pub const REG_PRETRIGGER_AMAX: u32 = 0x20;

/// Compute the FELib byte address for a per-channel register.
#[inline]
pub fn channel_register_byte_addr(channel: u8, word_offset: u32) -> u32 {
    let word_addr = PAGE_BASE + (channel as u32) * PAGE_STRIDE + word_offset;
    word_addr * 4
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn register_offsets_are_distinct() {
        let offsets = [
            REG_SELECTOR_WAVE,
            REG_PRETRIGGER_INPUT,
            REG_POLARITY,
            REG_OFFSET,
            REG_THRS,
            REG_TRIG_K,
            REG_TRIG_M,
            REG_TRAP_K,
            REG_TRAP_M,
            REG_DECONV_M,
            REG_TRAP_GAIN,
            REG_BL_LEN,
            REG_BL_INIB,
            REG_SAMPLE_POS,
            REG_RUN_CFG,
            REG_AMAX_WINDOW,
            REG_AMAX_DELAY,
            REG_WINDOW_MAXIM,
            REG_AMAX_LEN,
            REG_BASELINE_DELAY,
            REG_BASELINE_LEN,
            REG_BASELINE_OFFSET,
            REG_PRETRIGGER_TRAP,
            REG_PRETRIGGER_AMAX,
        ];
        let mut sorted = offsets.to_vec();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(sorted.len(), offsets.len());
    }

    #[test]
    fn channel_addr_math() {
        // ch0 base byte addr = PAGE_BASE * 4
        assert_eq!(channel_register_byte_addr(0, 0), PAGE_BASE * 4);
        // ch1 = ch0 + PAGE_STRIDE * 4 (byte units)
        assert_eq!(
            channel_register_byte_addr(1, 0),
            channel_register_byte_addr(0, 0) + PAGE_STRIDE * 4
        );
    }
}
