// AUTO-GENERATED by `cargo run --bin amax_codegen`. Do not edit by hand.
//
// Sources:
// - AMAX_firmware32_channel_4input_caenlist/output/output/RegisterFile.json
// - tools/amax_viewer/fw_params.json

import type { ChannelParamDef } from '../components/channel-table/channel-table.component';

export interface AMaxChannelConfig {
  /** 1-bit Wave Selector */
  selector_wave?: number;
  /** 32-bit Pretrig Input */
  pretrigger_input?: number;
  /** 1-bit Polarity */
  polarity?: number;
  /** 16-bit DC Offset */
  offset?: number;
  /** 32-bit Threshold */
  thrs?: number;
  /** 16-bit Fast Trig Rise */
  trig_k?: number;
  /** 16-bit Fast Trig Decay */
  trig_m?: number;
  /** 16-bit Trap Rise */
  trap_k?: number;
  /** 16-bit Trap Decay */
  trap_m?: number;
  /** 24-bit Deconvolution */
  deconv_m?: number;
  /** 24-bit Trap Gain */
  trap_gain?: number;
  /** 4-bit BL Length (MCA) */
  bl_len?: number;
  /** 16-bit BL Inhibit */
  bl_inib?: number;
  /** 16-bit Sample Pos */
  sample_pos?: number;
  /** 1-bit Run Enable */
  run_cfg?: number;
  /** 32-bit AMax Window */
  amax_window?: number;
  /** 32-bit AMax Delay */
  amax_delay?: number;
  /** 32-bit Max Window */
  window_maxim?: number;
  /** 16-bit AMax Length */
  amax_len?: number;
  /** 32-bit BL Delay (AMax) */
  baseline_delay?: number;
  /** 16-bit BL Length (AMax) */
  baseline_len?: number;
  /** 16-bit BL Offset (AMax) */
  baseline_offset?: number;
  /** 32-bit Pretrig Trap */
  pretrigger_trap?: number;
  /** 32-bit Pretrig AMax */
  pretrigger_amax?: number;
}

export const AMAX_INPUT_PARAMS: ChannelParamDef[] = [
  { key: 'amax.polarity', label: "Polarity", type: 'enum', options: ["0", "1"] },
  { key: 'amax.offset', label: "DC Offset", type: 'number', min: 0, max: 65535, step: 1 },
  { key: 'amax.run_cfg', label: "Run Enable", type: 'enum', options: ["0", "1"] },
];

export const AMAX_TRIGGER_PARAMS: ChannelParamDef[] = [
  { key: 'amax.thrs', label: "Threshold", type: 'number', min: 0, max: 1000000, step: 1 },
  { key: 'amax.trig_k', label: "Fast Trig Rise", type: 'number', unit: "samp", min: 0, max: 65535, step: 1 },
  { key: 'amax.trig_m', label: "Fast Trig Decay", type: 'number', unit: "samp", min: 0, max: 65535, step: 1 },
];

export const AMAX_ENERGY_PARAMS: ChannelParamDef[] = [
  { key: 'amax.trap_k', label: "Trap Rise", type: 'number', unit: "samp", min: 0, max: 65535, step: 1 },
  { key: 'amax.trap_m', label: "Trap Decay", type: 'number', unit: "samp", min: 0, max: 65535, step: 1 },
  { key: 'amax.deconv_m', label: "Deconvolution", type: 'number', min: 0, max: 16777215, step: 1 },
  { key: 'amax.trap_gain', label: "Trap Gain", type: 'number', min: 0, max: 16777215, step: 1 },
  { key: 'amax.bl_len', label: "BL Length (MCA)", type: 'number', min: 0, max: 15, step: 1 },
  { key: 'amax.bl_inib', label: "BL Inhibit", type: 'number', unit: "samp", min: 0, max: 65535, step: 1 },
  { key: 'amax.sample_pos', label: "Sample Pos", type: 'number', unit: "samp", min: 0, max: 65535, step: 1 },
  { key: 'amax.amax_window', label: "AMax Window", type: 'number', unit: "samp", min: 0, max: 1000000, step: 1 },
  { key: 'amax.amax_delay', label: "AMax Delay", type: 'number', unit: "samp", min: 0, max: 1000000, step: 1 },
  { key: 'amax.window_maxim', label: "Max Window", type: 'number', unit: "samp", min: 0, max: 1000000, step: 1 },
  { key: 'amax.amax_len', label: "AMax Length", type: 'number', unit: "samp", min: 0, max: 65535, step: 1 },
  { key: 'amax.baseline_delay', label: "BL Delay (AMax)", type: 'number', unit: "samp", min: 0, max: 1000000, step: 1 },
  { key: 'amax.baseline_len', label: "BL Length (AMax)", type: 'number', min: 0, max: 65535, step: 1 },
  { key: 'amax.baseline_offset', label: "BL Offset (AMax)", type: 'number', min: 0, max: 65535, step: 1 },
];

export const AMAX_WAVEFORM_PARAMS: ChannelParamDef[] = [
  { key: 'amax.selector_wave', label: "Wave Selector", type: 'enum', options: ["0", "1"] },
  { key: 'amax.pretrigger_input', label: "Pretrig Input", type: 'number', unit: "samp", min: 0, max: 1000000, step: 1 },
  { key: 'amax.pretrigger_trap', label: "Pretrig Trap", type: 'number', unit: "samp", min: 0, max: 1000000, step: 1 },
  { key: 'amax.pretrigger_amax', label: "Pretrig AMax", type: 'number', unit: "samp", min: 0, max: 1000000, step: 1 },
];

