// AUTO-GENERATED by `cargo run --bin amax_codegen`. Do not edit by hand.
//
// Sources:
// - FW/20260617/RegisterFile_17june.json
// - tools/amax_viewer/fw_params.json

import type { ChannelParamDef } from '../components/channel-table/channel-table.component';

export interface AMaxChannelConfig {
  /** 32-bit Pretrig Input */
  pretrigger_input?: number;
  /** 1-bit Polarity */
  polarity?: number;
  /** 16-bit Offset (Trapezoid) */
  offset?: number;
  /** 32-bit Threshold */
  thrs?: number;
  /** 16-bit Fast Trig Rise */
  trig_k?: number;
  /** 16-bit Fast Trig Decay */
  trig_m?: number;
  /** 16-bit Trap Rise */
  trap_k?: number;
  /** 16-bit Trap Decay */
  trap_m?: number;
  /** 24-bit Deconvolution */
  deconv_m?: number;
  /** 24-bit Trap Gain */
  trap_gain?: number;
  /** 4-bit BL Length (MCA) */
  bl_len?: number;
  /** 16-bit BL Inhibit */
  bl_inib?: number;
  /** 16-bit Sample Pos */
  sample_pos?: number;
  /** 1-bit Run Enable */
  run_cfg?: number;
  /** 32-bit AMax Window */
  amax_window?: number;
  /** 32-bit Max Window */
  window_maxim?: number;
  /** 16-bit AMax Length */
  amax_len?: number;
  /** 32-bit BL Delay (AMax) */
  baseline_delay?: number;
  /** 16-bit BL Length (AMax) */
  baseline_len?: number;
  /** 16-bit BL Offset (AMax) */
  baseline_offset?: number;
  /** 32-bit Delay Shaping */
  delay_shaping?: number;
  /** 32-bit Shaping Trigger */
  shap_trigg?: number;
  /** 32-bit Delay Debug */
  delay_debug?: number;
  /** 1-bit Enable Acquisition */
  enable_acq?: number;
  /** 8-bit E-Gate Trigger Sel */
  sel_trigger?: number;
  /** 16-bit AMax Gate Min */
  min_amax?: number;
  /** 16-bit Energy Gate Max */
  max_energy?: number;
  /** 16-bit Energy Gate Min */
  min_energy?: number;
  /** 16-bit AMax Gate Max */
  max_amax?: number;
}

/** Per-key default values from `fw_params.json` (FW developer defaults). */
export const AMAX_DEFAULTS: Record<string, number> = {
  'amax.pretrigger_input': 1800,
  'amax.polarity': 1,
  'amax.offset': 0,
  'amax.thrs': 20,
  'amax.trig_k': 10,
  'amax.trig_m': 12,
  'amax.trap_k': 500,
  'amax.trap_m': 550,
  'amax.deconv_m': 3499000,
  'amax.trap_gain': 2500,
  'amax.bl_len': 6,
  'amax.bl_inib': 1200,
  'amax.sample_pos': 510,
  'amax.run_cfg': 1,
  'amax.amax_window': 1000,
  'amax.window_maxim': 500,
  'amax.amax_len': 5,
  'amax.baseline_delay': 200,
  'amax.baseline_len': 6,
  'amax.baseline_offset': 1000,
  'amax.delay_shaping': 32,
  'amax.shap_trigg': 700,
  'amax.delay_debug': 0,
  'amax.enable_acq': 1,
  'amax.sel_trigger': 0,
  'amax.min_amax': 0,
  'amax.max_energy': 65535,
  'amax.min_energy': 0,
  'amax.max_amax': 65535,
};

/** All AMax dotted-path keys (`amax.<field>`). Used by the
 *  Settings expand/compress logic in `digitizer.service.ts`. */
export const AMAX_DOTTED_KEYS: readonly string[] = [
  'amax.pretrigger_input',
  'amax.polarity',
  'amax.offset',
  'amax.thrs',
  'amax.trig_k',
  'amax.trig_m',
  'amax.trap_k',
  'amax.trap_m',
  'amax.deconv_m',
  'amax.trap_gain',
  'amax.bl_len',
  'amax.bl_inib',
  'amax.sample_pos',
  'amax.run_cfg',
  'amax.amax_window',
  'amax.window_maxim',
  'amax.amax_len',
  'amax.baseline_delay',
  'amax.baseline_len',
  'amax.baseline_offset',
  'amax.delay_shaping',
  'amax.shap_trigg',
  'amax.delay_debug',
  'amax.enable_acq',
  'amax.sel_trigger',
  'amax.min_amax',
  'amax.max_energy',
  'amax.min_energy',
  'amax.max_amax',
];

/** Channel-param categories declared by `fw_params.json`.
 *  Mirrors the `AMAX_<CATEGORY>_PARAMS` arrays below; UI can
 *  iterate this list to render any future debug / housekeeping
 *  tabs without an additional codegen edit. */
export const AMAX_PARAM_CATEGORIES: readonly string[] = [
  'input',
  'trigger',
  'energy',
  'amax',
];

export const AMAX_INPUT_PARAMS: ChannelParamDef[] = [
  { key: 'amax.pretrigger_input', label: "Pretrig Input", type: 'number', unit: "samp", min: 0, max: 1000000, step: 1, tooltip: "FW reg PRETRIGGER_INPUT • word 0x00 (ch0 @ 0x800000)" },
  { key: 'amax.polarity', label: "Polarity", type: 'enum', options: ["0", "1"], numeric: true, tooltip: "FW reg POLARITY • word 0x01 (ch0 @ 0x800001)" },
  { key: 'amax.offset', label: "Offset (Trapezoid)", type: 'number', min: 0, max: 65535, step: 1, tooltip: "FW reg OFFSET • word 0x02 (ch0 @ 0x800002)" },
  { key: 'amax.run_cfg', label: "Run Enable", type: 'enum', options: ["0", "1"], numeric: true, tooltip: "FW reg RUN_CFG • word 0x0D (ch0 @ 0x80000D)" },
  { key: 'amax.delay_debug', label: "Delay Debug", type: 'number', unit: "samp", min: 0, max: 1000000, step: 1, tooltip: "FW reg delay_debug • word 0x18 (ch0 @ 0x800018)" },
  { key: 'amax.enable_acq', label: "Enable Acquisition", type: 'enum', options: ["0", "1"], numeric: true, tooltip: "FW reg ENABLE_ACQ • word 0x19 (ch0 @ 0x800019)" },
];

export const AMAX_TRIGGER_PARAMS: ChannelParamDef[] = [
  { key: 'amax.thrs', label: "Threshold", type: 'number', min: 0, max: 1000000, step: 1, tooltip: "FW reg THRS • word 0x03 (ch0 @ 0x800003)" },
  { key: 'amax.trig_k', label: "Fast Trig Rise", type: 'number', unit: "samp", min: 0, max: 65535, step: 1, tooltip: "FW reg TRIG_K • word 0x04 (ch0 @ 0x800004)" },
  { key: 'amax.trig_m', label: "Fast Trig Decay", type: 'number', unit: "samp", min: 0, max: 65535, step: 1, tooltip: "FW reg TRIG_M • word 0x05 (ch0 @ 0x800005)" },
  { key: 'amax.shap_trigg', label: "Shaping Trigger", type: 'number', unit: "samp", min: 0, max: 1000000, step: 1, tooltip: "FW reg SHAP_TRIGG • word 0x16 (ch0 @ 0x800016)" },
  { key: 'amax.sel_trigger', label: "E-Gate Trigger Sel", type: 'number', min: 0, max: 255, step: 1, tooltip: "FW reg sel_trigger • word 0x100 (ch0 @ 0x800100)" },
  { key: 'amax.min_amax', label: "AMax Gate Min", type: 'number', min: 0, max: 65535, step: 1, tooltip: "FW reg min_amax • word 0x101 (ch0 @ 0x800101)" },
  { key: 'amax.max_amax', label: "AMax Gate Max", type: 'number', min: 0, max: 65535, step: 1, tooltip: "FW reg max_amax • word 0x104 (ch0 @ 0x800104)" },
  { key: 'amax.min_energy', label: "Energy Gate Min", type: 'number', min: 0, max: 65535, step: 1, tooltip: "FW reg min_energy • word 0x103 (ch0 @ 0x800103)" },
  { key: 'amax.max_energy', label: "Energy Gate Max", type: 'number', min: 0, max: 65535, step: 1, tooltip: "FW reg max_energy • word 0x102 (ch0 @ 0x800102)" },
];

export const AMAX_ENERGY_PARAMS: ChannelParamDef[] = [
  { key: 'amax.trap_k', label: "Trap Rise", type: 'number', unit: "samp", min: 0, max: 65535, step: 1, tooltip: "FW reg TRAP_K • word 0x06 (ch0 @ 0x800006)" },
  { key: 'amax.trap_m', label: "Trap Decay", type: 'number', unit: "samp", min: 0, max: 65535, step: 1, tooltip: "FW reg TRAP_M • word 0x07 (ch0 @ 0x800007)" },
  { key: 'amax.deconv_m', label: "Deconvolution", type: 'number', min: 0, max: 16777215, step: 1, tooltip: "FW reg DECONV_M • word 0x08 (ch0 @ 0x800008)" },
  { key: 'amax.trap_gain', label: "Trap Gain", type: 'number', min: 0, max: 16777215, step: 1, tooltip: "FW reg TRAP_GAIN • word 0x09 (ch0 @ 0x800009)" },
  { key: 'amax.bl_len', label: "BL Length (MCA)", type: 'number', min: 0, max: 15, step: 1, tooltip: "FW reg BL_LEN • word 0x0A (ch0 @ 0x80000A)" },
  { key: 'amax.bl_inib', label: "BL Inhibit", type: 'number', unit: "samp", min: 0, max: 65535, step: 1, tooltip: "FW reg BL_INIB • word 0x0B (ch0 @ 0x80000B)" },
  { key: 'amax.sample_pos', label: "Sample Pos", type: 'number', unit: "samp", min: 0, max: 65535, step: 1, tooltip: "FW reg SAMPLE_POS • word 0x0C (ch0 @ 0x80000C)" },
  { key: 'amax.delay_shaping', label: "Delay Shaping", type: 'number', unit: "samp", min: 0, max: 1000000, step: 1, tooltip: "FW reg DELAY_SHAPING • word 0x15 (ch0 @ 0x800015)" },
];

export const AMAX_AMAX_PARAMS: ChannelParamDef[] = [
  { key: 'amax.amax_window', label: "AMax Window", type: 'number', unit: "samp", min: 0, max: 1000000, step: 1, tooltip: "FW reg AMAX_window • word 0x0E (ch0 @ 0x80000E)" },
  { key: 'amax.window_maxim', label: "Max Window", type: 'number', unit: "samp", min: 0, max: 1000000, step: 1, tooltip: "FW reg WINDOW_MAXIM • word 0x0F (ch0 @ 0x80000F)" },
  { key: 'amax.amax_len', label: "AMax Length", type: 'number', unit: "samp", min: 0, max: 65535, step: 1, tooltip: "FW reg AMAX_len • word 0x10 (ch0 @ 0x800010)" },
  { key: 'amax.baseline_delay', label: "BL Delay (AMax)", type: 'number', unit: "samp", min: 0, max: 1000000, step: 1, tooltip: "FW reg baseline_delay • word 0x11 (ch0 @ 0x800011)" },
  { key: 'amax.baseline_len', label: "BL Length (AMax)", type: 'number', min: 0, max: 65535, step: 1, tooltip: "FW reg baseline_len • word 0x12 (ch0 @ 0x800012)" },
  { key: 'amax.baseline_offset', label: "BL Offset (AMax)", type: 'number', min: 0, max: 65535, step: 1, tooltip: "FW reg baseline_offset • word 0x13 (ch0 @ 0x800013)" },
];

/** Maps each AMax category name to its params array. The UI
 *  iterates `AMAX_PARAM_CATEGORIES` over this map to render tabs,
 *  so a new firmware category auto-appears with no hand-edit. */
export const AMAX_PARAMS_BY_CATEGORY: Record<string, ChannelParamDef[]> = {
  'input': AMAX_INPUT_PARAMS,
  'trigger': AMAX_TRIGGER_PARAMS,
  'energy': AMAX_ENERGY_PARAMS,
  'amax': AMAX_AMAX_PARAMS,
};

/** AMax board-level (global) writable register set —
 *  firmware-wide toggles like the debug-FW `ENABLE_ACQ`. */
export interface AMaxBoardConfig {
}

/** Per-key default values for board-level registers. */
export const AMAX_BOARD_DEFAULTS: Record<string, number> = {
};

/** Board-level dotted-path keys (`amax.board.<field>`). */
export const AMAX_BOARD_DOTTED_KEYS: readonly string[] = [
];

/** Board-level parameter UI definitions. */
export const AMAX_BOARD_PARAMS: ChannelParamDef[] = [
];
