//! AUTO-GENERATED by `cargo run --bin amax_codegen`. Do not edit by hand.
//!
//! Sources:
//! - FW/13july2026/RegisterFile13iulie.json
//! - tools/amax_viewer/fw_params.json
//!
//! AMax custom-firmware per-channel writable register set.
//! Each field maps 1:1 to one user-register write at
//! `(PAGE_BASE + channel * PAGE_STRIDE + REG_<NAME>) * 4` byte
//! address (see `amax_registers_generated::channel_register_byte_addr`).

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AMaxChannelConfig {
    /// 32-bit Pretrig Input, unit: samp (FW reg `PRETRIGGER_INPUT`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pretrigger_input: Option<u32>,
    /// 1-bit Polarity (FW reg `POLARITY`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub polarity: Option<u32>,
    /// 16-bit Offset (Trapezoid) (FW reg `OFFSET`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub offset: Option<u32>,
    /// 32-bit Threshold (FW reg `THRS`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thrs: Option<u32>,
    /// 16-bit Fast Trig Rise, unit: samp (FW reg `TRIG_K`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trig_k: Option<u32>,
    /// 16-bit Fast Trig Decay, unit: samp (FW reg `TRIG_M`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trig_m: Option<u32>,
    /// 16-bit Trap Rise, unit: samp (FW reg `TRAP_K`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trap_k: Option<u32>,
    /// 16-bit Trap Decay, unit: samp (FW reg `TRAP_M`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trap_m: Option<u32>,
    /// 24-bit Deconvolution (FW reg `DECONV_M`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deconv_m: Option<u32>,
    /// 24-bit Trap Gain (FW reg `TRAP_GAIN`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trap_gain: Option<u32>,
    /// 4-bit BL Length (MCA) (FW reg `BL_LEN`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bl_len: Option<u32>,
    /// 16-bit BL Inhibit, unit: samp (FW reg `BL_INIB`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bl_inib: Option<u32>,
    /// 16-bit Sample Pos, unit: samp (FW reg `SAMPLE_POS`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sample_pos: Option<u32>,
    /// 1-bit Run Enable (FW reg `RUN_CFG`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub run_cfg: Option<u32>,
    /// 32-bit AMax Window, unit: samp (FW reg `AMAX_window`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amax_window: Option<u32>,
    /// 32-bit Max Window, unit: samp (FW reg `WINDOW_MAXIM`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub window_maxim: Option<u32>,
    /// 16-bit AMax Length, unit: samp (FW reg `AMAX_len`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amax_len: Option<u32>,
    /// 32-bit BL Delay (AMax), unit: samp (FW reg `baseline_delay`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub baseline_delay: Option<u32>,
    /// 16-bit BL Length (AMax) (FW reg `baseline_len`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub baseline_len: Option<u32>,
    /// 16-bit BL Offset (AMax) (FW reg `baseline_offset`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub baseline_offset: Option<u32>,
    /// 32-bit Delay Shaping, unit: samp (FW reg `DELAY_SHAPING`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delay_shaping: Option<u32>,
    /// 32-bit Shaping Trigger, unit: samp (FW reg `SHAP_TRIGG`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub shap_trigg: Option<u32>,
    /// 1-bit Enable Acquisition (FW reg `ENABLE_ACQ`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enable_acq: Option<u32>,
    /// 32-bit Trigger logic width (FW reg `select_width`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub select_width: Option<u32>,
    /// 16-bit AMax Gate Max (FW reg `maxim_pid`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub maxim_pid: Option<u32>,
    /// 16-bit Energy Gate Min (FW reg `valoare_minima_energy`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub valoare_minima_energy: Option<u32>,
    /// 16-bit AMax Gate Min (FW reg `minim_pid`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub minim_pid: Option<u32>,
    /// 16-bit Energy Gate Max (FW reg `valoare_maxim_energy`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub valoare_maxim_energy: Option<u32>,
}

/// AMax board-level (global) writable register set. Used for
/// firmware-wide toggles like the debug-FW `ENABLE_ACQ` switch.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AMaxBoardConfig {}
