//! Auto-generated FFI bindings for CAENDigitizer Library
//!
//! Generated by bindgen from CAENDigitizer.h v2.19.0

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/caen_digitizer_bindings.rs"));
