apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8181
    database: delila
    isDefault: true
    editable: true
    jsonData:
      httpMode: POST
