//! Internal proc-macro helpers for delila-rs.
//!
//! Currently exposes a single derive: [`MergeOverride`].
//!
//! # `#[derive(MergeOverride)]`
//!
//! Generates `pub fn merge_from(&mut self, ov: &Self)` for a struct of `Option<T>` /
//! `HashMap<K, V>` fields. For each `Option<T>` field, if `ov.<f>.is_some()` the
//! value is cloned into `self.<f>`; for each `HashMap<K, V>` field, the override
//! map is extended into `self.<f>`. Other field shapes are rejected at compile
//! time.
//!
//! Replaces the hand-maintained `merge_field!(name)` listing in
//! `src/config/digitizer.rs::ChannelConfig::get_channel_config`. The previous
//! manual list silently dropped overrides for any field that was added to the
//! struct but forgotten in the merge list — `MergeOverride` makes that bug class
//! impossible by deriving the merge from the struct definition.

use proc_macro::TokenStream;
use quote::quote;
use syn::{
    parse_macro_input, Data, DeriveInput, Field, Fields, GenericArgument, PathArguments, Type,
};

/// Field classification for the merge codegen.
enum FieldKind {
    /// `Option<T>` — copy from override iff `is_some()`.
    Option,
    /// `HashMap<K, V>` — extend the override entries into self.
    HashMap,
    /// Anything else — fail compilation, force the author to opt out
    /// explicitly (currently no opt-out attribute is needed because the
    /// real `ChannelConfig` only uses `Option<T>` and `HashMap<K, V>`).
    Other,
}

fn classify(ty: &Type) -> FieldKind {
    let Type::Path(tp) = ty else {
        return FieldKind::Other;
    };
    let Some(seg) = tp.path.segments.last() else {
        return FieldKind::Other;
    };
    match seg.ident.to_string().as_str() {
        "Option" => FieldKind::Option,
        "HashMap" => FieldKind::HashMap,
        _ => FieldKind::Other,
    }
}

#[allow(dead_code)]
fn inner_of_option(ty: &Type) -> Option<&Type> {
    let Type::Path(tp) = ty else { return None };
    let seg = tp.path.segments.last()?;
    if seg.ident != "Option" {
        return None;
    }
    let PathArguments::AngleBracketed(ab) = &seg.arguments else {
        return None;
    };
    ab.args.iter().find_map(|arg| match arg {
        GenericArgument::Type(t) => Some(t),
        _ => None,
    })
}

/// Derive `merge_from(&mut self, ov: &Self)` over all `Option<T>` and
/// `HashMap<K, V>` fields. Override fields with `Some` value or non-empty
/// map entries win over `self`.
#[proc_macro_derive(MergeOverride)]
pub fn derive_merge_override(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let name = &input.ident;
    let (impl_g, ty_g, where_g) = input.generics.split_for_impl();

    let Data::Struct(data) = &input.data else {
        return syn::Error::new_spanned(&input, "MergeOverride only supports structs")
            .to_compile_error()
            .into();
    };
    let Fields::Named(named) = &data.fields else {
        return syn::Error::new_spanned(
            &data.fields,
            "MergeOverride only supports structs with named fields",
        )
        .to_compile_error()
        .into();
    };

    let mut stmts = Vec::with_capacity(named.named.len());
    for Field { ident, ty, .. } in &named.named {
        let f = ident.as_ref().expect("named field");
        match classify(ty) {
            FieldKind::Option => {
                stmts.push(quote! {
                    if ov.#f.is_some() {
                        self.#f = ov.#f.clone();
                    }
                });
            }
            FieldKind::HashMap => {
                stmts.push(quote! {
                    for (k, v) in &ov.#f {
                        self.#f.insert(k.clone(), v.clone());
                    }
                });
            }
            FieldKind::Other => {
                return syn::Error::new_spanned(
                    ty,
                    "MergeOverride only supports `Option<T>` and `HashMap<K, V>` fields. \
                     Add an explicit handler to delila-derive if you need other shapes.",
                )
                .to_compile_error()
                .into();
            }
        }
    }

    let expanded = quote! {
        impl #impl_g #name #ty_g #where_g {
            /// Merge `ov` into `self`: every `Some` override field clones
            /// over the existing value; every `HashMap` override entry is
            /// extended into the existing map.
            ///
            /// Generated by `#[derive(MergeOverride)]`
            /// (`delila-derive::MergeOverride`).
            pub fn merge_from(&mut self, ov: &Self) {
                #(#stmts)*
            }
        }
    };

    expanded.into()
}
